on: [pull_request]
name: Static analysis

jobs:
  statics:
    name: Composer verify
    runs-on: ubuntu-22.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Static tests
        run: composer statics --strict